# Generated by Django 3.0.6 on 2020-07-27 05:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.models.Users.upload_photo),
        ),
    ]
