# Generated by Django 3.0.6 on 2020-07-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(default='', max_length=50)),
                ('seller_age', models.IntegerField(default=18)),
                ('seller_image', models.ImageField(blank=True, upload_to='')),
                ('seller_address', models.CharField(max_length=250)),
                ('seller_contact', models.IntegerField(default='')),
                ('seller_is_approved', models.BooleanField(default=True)),
            ],
        ),
    ]
